<<<<<<< HEAD
language: node_js
node_js:
  - "8"
  - "9"
services: mongodb  
cache:  
=======
# .travis.yml file
language: node_js
node_js:
  - "8"
services: mongodb
cache:
>>>>>>> adding .travis.yml and deploy.sh files
  directories:
    - "node_modules"
sudo: false
install:
<<<<<<< HEAD
  - npm install
script:
  - npm run lint
  - npm test
=======
  -npm install
script:
  - npm test
  
>>>>>>> adding .travis.yml and deploy.sh files
